version: "3"

services:
   influxdb_power:
      image: hypriot/rpi-influxdb
      ports: 
         - "8086:8086"
      container_name: influxdb_pow
      restart: always
      environment:
         - INFLUXDB_INIT_PWD= "admin"
         - PRE_CREATE_DB= emon
      volumes:
         - ./sm-timeseries_database_sds/data:/var/lib/influxdb
      networks:
            shoestring-internal:
               aliases:
                 - influx.docker.local


   grafana_power:
      image: grafana/grafana
      ports: 
         - "3000:3000"
      container_name: grafana_pow
      restart: always
      volumes:
         - grafana-db:/var/lib/grafana
         - grafana-log:/var/log/grafana
         - grafana-conf:/etc/grafana
         - ./brand:/var/lib/grafana/plugins
      environment:
         - GF_AUTH_DISABLE_LOGIN_FORM=true
         - GF_AUTH_ANONYMOUS_ENABLED=true
         - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
         - GF_SECURITY_ALLOW_EMBEDDING=true
      networks:
            shoestring-internal:
               aliases:
                 - grafana.docker.local
      depends_on:
           - influxdb_power


   mosquitto_power:
       image: pascaldevink/rpi-mosquitto
       ports:
          - "1883:1883"
       container_name: mosquitto_pow
       restart: always
       volumes:
           - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
           - ./mosquitto/data:/mosquitto/data
           - ./mosquitto/log:/mosquitto/log
       networks:
            shoestring-internal:
               aliases:
                 - mqtt.docker.local


   sensor_mfm:
        build: ./sensor
        container_name: sensor
        privileged: true
        restart: always
        volumes:
           - ./sensor/code:/app/
           - ./sensor/config:/app/config
           - /var/logs/sensor:/var/logs/sensor
        networks:
            shoestring-internal:
               aliases:
                 - sensor.docker.local
        depends_on:
             - influxdb_power
             - mosquitto_power


networks:
     shoestring-internal:



volumes:
     grafana-db:
        driver: local
     grafana-log:
        driver: local
     grafana-conf:
        driver: local